### ISSUE TITLE
ROADMAP: Snippet

### ISSUE THREAD

**Issue by teesloane** [the-heap/Emojions#15]
**Read this to:**

Understand the road map for the emojion bar `snippet`. 

**I expect you to know:**

Our general [roadmap](https://github.com/the-heap/Emojions/issues/1) 
[How we are architecting the snippet code](https://github.com/the-heap/Emojions/issues/3)

# Overview:

The Emojion bar `snippet` is one component of three in this project.  We need to create an embeddable javascript snippet that a user can embed into their own website. The snippet's job is to find a way to create an emoji bar wherever the User (who installed the snippet) wants it to go.

# Wireframe
Here is a basic wireframe that we will be following:

![emojion bar mockup](https://cloud.githubusercontent.com/assets/12987958/25552246/a334ed2c-2c62-11e7-8e6c-ba123b1bc231.png)

# Example site

We use a dummy example page to test the snippet on. It is at the root of the `snippet` folder as `example.html`. 

# Issue List 
The following steps are a general guideline (estimation, on my behalf) of how we might accomplish what we need to do. Each step has it's own issue (look for the number at the end of the line 👑)

- [ ] Make our function pipeline async-ready #9 
- [x] Template HTTP requests for hooking counters up to a backend. #10
- [ ] write unit tests for each function in the render pipeline. #13
- [x] Architecture: Create a function pipeline for organizing the snippet #3
- [x] Find a way to mount the emoji bar into the dom #4
- [x] Set up JEST for testing #12
- [x] create a function that spits out a stylesheet that can style our emojion bar #7 
- [x] Manage the state of the emoji count (how many times an emoji has been clicked) #5 
- [x] Adaptive styling #8 
- [x] Set up CIRCLECI for automatically running our jest tests. #11
