### ISSUE TITLE
ROADMAP: Emoji Picker Client

### ISSUE THREAD

**Issue by teesloane** [the-heap/Emojions#23]
**Read this to:**

Understand the road map for the emojion bar `Emoji Picker`

**I expect you to know:**

- Our general [roadmap](https://github.com/the-heap/Emojions/issues/1) 
- What our `snippet` does

# Overview:

The client is a small webapp that will exist to serve one primary function: allowing a user (someone who wants to embed an emojion bar on their site) to customize their emoji bar — choosing which emoji's show up.

This part of the project will be built with Elm, if we get to it. I'd like to build it with Elm to try something new, get better at functional programming, as well as attract other programmers with different perspectives / interests.

# Wireframe
Here is a basic wireframe that we will be following:

TODO

# Issue List 
The following steps are a general guideline (estimation, on my behalf) of how we might accomplish what we need to do. Each step has it's own issue (look for the number at the end of the line 👑)

- [x] Setup the repo with the latest version of elm #16 
- [x] Try and get a very basic site of elm up and running #17 
- [x] Research previous emoji packages that exist for elm and what they do. #18 
- [x] Scaffold out the model, view and update functions as pseudocode #19 
- [x] Allow users to pick emojis to use in their emojion bar #21 
- [ ] Generate the snippet once^ emojis are chosen #20 
- [ ] Should provide instructions on how a user installs their snippet #22
