### ISSUE TITLE
ROADMAP: API

### ISSUE THREAD

**Issue by teesloane** [the-heap/Emojions#54]
**Read this to:**

Understand the road map for the emojion bar `api`. 

**I expect you to know:**

Our general [roadmap](https://github.com/the-heap/Emojions/issues/1) 
[How we are architecting the snippet code](https://github.com/the-heap/Emojions/issues/3)

# Overview:

The API is sort of the final puzzle piece to finish the snippet. Without an API anybody can still use our Snippet; but it's a `byodb` - bring your own database` - they need to hook up the snippet to whatever their database system is. 

If we want to provide full ease of use; it would be idea to provide a back end api that stores and retrieves emoji counts per user. 

# Usage Example

- User comes to our `client` app and picks out some emojis they want to fill for their own personal emoji bar.
- The `client` app will allow a user to specific the endpoint for their emojion bars to be saved to and retrieved from -- this is the url for an instance of this custom api. 
- The user is able to load up an instance of our api quickly and easily; set up to work out of the box with the snippet.  

# Issue List 
The following steps are a general guideline (estimation, on my behalf) of how we might accomplish what we need to do. Each step has it's own issue (look for the number at the end of the line 👑)

- [ ] Setup flask for our backend #50
- [ ] Figure out a DB solution #52
- [ ] Create our main endpoint #53
