### ISSUE TITLE
Make the pipe async!

### ISSUE THREAD

**Issue by teesloane** [the-heap/Emojions#9]
We need to make our function pipe be able to do things asynchronously; at some point in time we want this snippet to make a network call — an asychronous action. 

Currently, our function pipe executions every function one after another, and will not launch another function until it has completed the execution context of the current function.

How can we make the `pipe` function handle taking functions that perform asynchronously? 

# TODO

Backend:
- [x] Install [json-server](https://github.com/typicode/json-server)
- [x] Create a mock database that returns emoji data[1] 

FrontEnd
- [ ] Add a constant to the emojion snippet that identifies a user uniquely -> this will get sent to the back end.
- [ ] On site load, check the backend to see if the current site exists (as a user) in the back end - 
  - [ ] If so, retrieve the emoji data from the back end by querying by the user's id.
  - [ ] If not, create an instance of the user based on some kind of special hash. ie - a user should put in a unique id based on their site name + perhaps a uuid and then that will identify them in the DB. (this will probably be refactored in the future) 
- [ ] Make a fetch to our dummy service  (don't worry about async'ing yet - just get the fetch working!)
- [ ] After we have a successful request, find a way to make our pipe async successfully. 

**Footnotes**
1. the structure of the returned data should probably be structured similarly to how it looks in the front end currently. Also, we'll have to make sure that the mounting point strings (ie. where a user would want to mount the emojion bar) corresponds to the data structure coming from the back end. 

2. If a user's mounting points aren't in the back end, it should _create_ a record that corresponds to it; but this all needs to be unique to the user.

**Comment by mackiedrew** [comment]
So the way I see it we have three options:

## Async/Await
Basically impossible considering it's not even in ES7 yet. No browser support.

## [Promises](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Promise)
This is my personal favourite, it has pretty wide support in browsers, but it will mean we can construct a pipe function that does not require any special changes to the functions that it uses in the pipe.

## Callbacks
We could make the pipe call-back based, but this may require at least some of the function called in the pipe require special arguments and boilerplate. Which makes me sad... Maybe another templating funciton can be used so noone ever has to think about it.

**Comment by quietcoding** [comment]
I'm gonna go on a hunch here and say that Promises are the way to go. I'll give it a shot and get back to you (assuming someone else hasn't done it yet).

**Comment by teesloane** [comment]
@qazqwezxc thanks for weighing in. I've got one or two people who are interested in it, but haven't heard too much from them. Feel free to take a crack at it, or to mention it on gitter to see if anyone corresponds. Could be a cool one to collaborate on too. But feel free to tackle it solo!

**Comment by quietcoding** [comment]
Thanks, I'm a bit new to this... all of this js good stuff. 

Can you give me some insight on this? What are your thoughts on converting all the pipe functions into promises. Then the pipeline is then converted to executing each function on a '.then' basis. Trudging through this for the first time, let me know!

Edit:
I think what I'll do is add promises to the existing functions, 'then' execute them through the render constant asynchronously. Hopefully it's a trivial solution... only challenge for me is figuring out a simple way to implement this into what already exists in index.js

Edit x2:
I think I have a possible solution. Anyone can feel free to chip in.
- Initialize promise based off of first function call used by pipe
- Take each state from each successful resolve and pass it to the next function
- Continue until finished

Another possibility would be to have individual pipes operating asynchronously and updating only what is needed. This can require a bit more thought if needed.

**Comment by ChristofLee** [comment]
I was interested in this to. My question is *does every function need to be asynchronous?*
For example, do we need to wait for a _http request_ in order to _start adding styles to the page?_

Here is some super dirty pseudo code of what I'm thinking.
```
promise.all
    sendHTTPRequest()
    addEmojionBarContainers()
    styleEmojionBar()
.then
    dealWithHTTPRequest()
```
Is this our intention? Any help would be *much appreciated, as always.*

**Comment by teesloane** [comment]
These are good questions that I am not sure how to answer yet. @mackiedrew had some input on a promise based approach (can you weight in @mackiedrew ?)

Many of the functions do not need to be async -- only really one or two:

- `getEmojionCountFromServer()` -> this fills up the state.emojions struct with the data needed to display in the page (the emoji and it's respective count).

- `sendEmojionCountToServer()`. -> Take emojii count / data -> send to a server / database. 

I'm going to create a task list at the [top of this issue](https://github.com/the-heap/Emojions/issues/9#issue-225281961) for a checklist of things we need to do I think. Before we write any async code, we're going to need to write a dummy back end service that can pretend to be a server. I'll [set something up with json-server](https://github.com/typicode/json-server) ... I just learned about this tool - looks really useful.

**Comment by mackiedrew** [comment]
Hey sorry, contacts have taken me again!

There is a little overhead but I don't think wrapping each sync function in
a promise is a problem. It will automatically trigger the resolve and
therefore not kill performance too much.

If you want to test the asynchronous pipe you can feed it setTimeouts,
which will simulate a request period.

**Comment by teesloane** [comment]
Thanks @mackiedrew, no worries. We'll figure this out Team!

I have updated the issue at the top with information about how we can tackle this. If You want to tackle a sub set of this issue, please do and make a PR against the branch specifically for this issue (not against development)

**Comment by quietcoding** [comment]
Hey @teesloane,

What are your suggestions to creating the backend database?
After a little thought, it looks like we could create a RESTful API which would need some unique way of identifying every emojion bar utilized. Either that, or they could just feed into 1 monolith counter for different emoji's used?

I think one of the ways to tackle the backend will be to create an unique instance ID for each emojion bar used. This unique instance ID will then be added to the db.json backend where we could 'asynchronously' keep track of the emojis being used.

In Pseudo code words:
Frontend:
- Create emojion bar
- bar has associated unique ID

backend:
- GET unique ID for emojion bar, otherwise POST new empty data for it into database
- keep track of data asynchronously for emoji tallys

Let me know what you think!

Edit:
- woops, just read the issue update... working on it

I've created a new issue to tackle the backend part myself. Fun stuff :)

**Comment by teesloane** [comment]
>I think one of the ways to tackle the backend will be to create an unique instance ID for each emojion bar used. This unique instance ID will then be added to the db.json backend where we could 'asynchronously' keep track of the emojis being used.

Yep, that's pretty much what I was thinking !! 

Thanks for adding your voice here. Looking forward to seeing what we can do!
